//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AddressModel
    {
        [Key]
        public int addressID { get; set; }
        public int customerID { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string postalCode { get; set; }
    
        public virtual CustomerModel Customer { get; set; }
    }
}
