//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using DbConnection;
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminModel
    {
        [Key]
        public int adminID { get; set; }
        [Required]
        [Display(Name = "AdminName")]
        public string adminName { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string email { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        public string confirmPassword { get; set; }

        public bool isValid(string email, string password)
        {
            DataContext context = new DataContext();
            var u = (from s in context.AdminModelSet
                     where s.email == email && s.password == password
                     select s).ToList();
            if (u.Count > 0)
                return true;
            else
                return false;
        }
    }
}
