//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BillingModel
    {
        [Key]
        public int billingID { get; set; }
        public int customerID { get; set; }
        public string cardNumber { get; set; }
        public string cardType { get; set; }
        public decimal cvv { get; set; }
        public System.DateTime expDate { get; set; }
        public string cardHolderName { get; set; }
    
        public virtual CustomerModel Customer { get; set; }
    }
}
