//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductModel()
        {
            this.OrderDetails = new HashSet<OrderDetailModel>();
        }

        [Key]
        public int productID { get; set; }

        [DisplayName("Product Name")]
        [Required(ErrorMessage = "Product Name is required")]
        [StringLength(50, ErrorMessage = "Product Name has to be between 2 and 50 words", MinimumLength = 2)]
        public string productName { get; set; }

        [DisplayName("Product Description")]
        [StringLength(255, ErrorMessage = "Product Description has to be between 10 and 50 words", MinimumLength = 10)]
        public string productDescription { get; set; }

        [DisplayName("Product Category")]
        [Required(ErrorMessage = "Category Name is required")]
        public Nullable<int> prodCategoryID { get; set; }

        [DisplayName("Price")]
        [Required(ErrorMessage = "Price is required")]
        public decimal price { get; set; }

        [DisplayName("Vendor")]
        [Required(ErrorMessage = "Vendor is required")]
        //[StringLength(50, ErrorMessage = "Vendor has to be between 2 and 50 words", MinimumLength = 2)]
        public string vendor { get; set; }

        [DisplayName("Quantity in Stock")]
        [Required(ErrorMessage = "Quantity in Stock is required")]
        //[Range(0, 250, ErrorMessage = "Quantity must be between 0 and 250")]
        public int quantityInStock { get; set; }

        [DisplayName("Product Image")]
        public byte[] productImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailModel> OrderDetails { get; set; }
        public virtual ProductCategoryModel ProductCategory { get; set; }
        public List<ProductCategoryModel> AllocatedCategory { get; set; }
    }
}
