//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyalotV1._0.Models
{
    using DbConnection;
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminModel
    {
        [Key]
        public int adminID { get; set; }
        public string adminName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string confirmPassword { get; set; }

        //DataContext context = new DataContext();
        //var u = (from s in context.AdminModelSet
        //         where s.adminName == adminName && s.email == email && s.password == password
        //         select s).ToList();
        //    if (u.Count > 0)
        //        return true;
        //    else
        //        return false;
    }
}
