//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyalotV1._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class OrderDetailModel
    {
        [Key]
        public int orderDetailsID { get; set; }
        public int orderID { get; set; }
        public int productID { get; set; }
        public int quantityOrdered { get; set; }
        public decimal priceEach { get; set; }
    
        public virtual OrderModel Order { get; set; }
        public virtual ProductModel Product { get; set; }
    }
}
